AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template for s3 bucket 
    
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Description: Creating Amazon S3 bucket from CloudFormation
    # Properties:
    #   BucketName: my-s3-bucket-Divisha-wonder-girl
Outputs:
  S3Bucket:
    Value: !Ref S3Bucket
    Description: Bucket Created using this template.
